FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux \
go build \
-ldflags="-s -w" \
-o wallet-service \
./cmd/server

FROM alpine:3.21

RUN adduser -D appuser

USER appuser

WORKDIR /app

COPY --from=builder /app/wallet-service .

EXPOSE 8080

CMD ["./wallet-service"]